USE [Following]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Airline](
	[CompanyCode] [int] IDENTITY(1,1) NOT NULL,
	[HebrewCompanyName] [nvarchar](50) NULL,
	[EnglishCompanyName] [nvarchar](50) NULL,
 CONSTRAINT [PK_tbl_airline] PRIMARY KEY CLUSTERED 
(
	[CompanyCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
