USE [Following]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [BusesCost](
	[BusesCostCode] [int] IDENTITY(1,1) NOT NULL,
	[BusCompanyCode] [int] NOT NULL,
	[NumberSeats] [int] NULL,
 CONSTRAINT [PK_tbl_busesCost] PRIMARY KEY CLUSTERED 
(
	[BusesCostCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]